import fs from 'node:fs';
import path from 'node:path';
import { SOURCES } from '../common/schema.js';
import { currentIsoWeek, weekDistance } from '../common/week.js';
import { flagString, parseFlags, readEnvelope, readLatest } from './workspace.js';

const flags = parseFlags(process.argv.slice(2));
const brand = flagString(flags, 'brand', 'nanorevive');
const period = flagString(flags, 'period', currentIsoWeek()) || currentIsoWeek();
const outDir = flagString(flags, 'out', path.resolve(process.cwd(), '..', `brand-${brand}`));

const latest = readLatest(outDir);
const lines: string[] = [];

const title = `${capitalize(brand)} — context for week ${period}`;
lines.push(`# ${title}`);
lines.push('');
lines.push('> Auto-generated by `context-tooling`. This is the summary an agent should read first.');
lines.push('> Raw, schema-validated data lives under `data/<source>/<period>.json`; this file only summarizes it.');
lines.push('');

// Freshness table.
lines.push('## Freshness');
lines.push('');
lines.push('| Source | Status | Latest period | Stale? |');
lines.push('|---|---|---|---|');
for (const source of SOURCES) {
  const env = readEnvelope(outDir, source, period);
  const latestPeriod = latest[source] ?? '(none)';
  const stale = env ? weekDistance(period, latestPeriod) < 0 : true;
  const status = env ? env.status : 'missing';
  lines.push(`| ${source} | ${status} | ${latestPeriod} | ${stale ? 'yes' : 'no'} |`);
}
lines.push('');

// Per-source summary.
lines.push('## Sources');
lines.push('');
for (const source of SOURCES) {
  const env = readEnvelope(outDir, source, period);
  lines.push(`### ${source}`);
  lines.push('');
  if (!env) {
    lines.push(`_No data for ${period}. Latest available: ${latest[source] ?? '(none)'}._`);
    lines.push('');
    continue;
  }
  lines.push(...renderSource(source, env.data));
  lines.push('');
}

lines.push('## How to use this file');
lines.push('');
lines.push(`- Find raw data for this brand and week at \`data/<source>/${period}.json\`.`);
lines.push('- The map of every brand/source/latest-week lives in `INDEX.md`.');
lines.push('- Run history and failure reasons are in `RUNS.md` (the only place with run timestamps).');
lines.push('');

fs.writeFileSync(path.join(outDir, 'CONTEXT.md'), lines.join('\n'));
process.stdout.write(`Wrote ${path.join(outDir, 'CONTEXT.md')}\n`);

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function money(n: unknown): string {
  const v = Number(n ?? 0);
  return `$${v.toFixed(2)}`;
}

function renderSource(source: string, data: any): string[] {
  switch (source) {
    case 'shopify':
      return renderShopify(data);
    case 'converge':
      return renderConverge(data);
    case 'reddit':
      return renderReddit(data);
    case 'richpanel':
      return renderRichpanel(data);
    case 'aircall':
      return renderAircall(data);
    default:
      return ['```json', JSON.stringify(data, null, 2), '```'];
  }
}

function renderShopify(d: any): string[] {
  const out = [
    `- Orders: ${d.orders?.count ?? 0} (${money(d.orders?.revenue)} revenue, ${d.orders?.units ?? 0} units)`,
    `- Refunds: ${d.refunds?.count ?? 0} (${money(d.refunds?.amount)})`,
    '',
    'Units by SKU:',
    '',
    '| SKU | Units | Revenue |',
    '|---|---|---|',
  ];
  for (const row of d.unitsBySku ?? []) {
    out.push(`| ${row.sku} | ${row.units} | ${money(row.revenue)} |`);
  }
  out.push('', 'Catalog:', '');
  for (const item of d.catalog ?? []) {
    out.push(`- ${item.sku} — ${item.title} (${item.productType})`);
  }
  return out;
}

function renderConverge(d: any): string[] {
  const out = [
    `- Attribution model: **${d.attributionModel}**`,
    `- Ad spend: ${money(d.adSpend)}`,
    `- Attributed revenue: ${money(d.attributedRevenue)}`,
    `- Blended ROAS: ${d.blendedRoas}`,
    '',
    '| Channel | Spend | Attributed revenue | ROAS |',
    '|---|---|---|---|',
  ];
  for (const row of d.byChannel ?? []) {
    out.push(`| ${row.channel} | ${money(row.spend)} | ${money(row.attributedRevenue)} | ${row.roas} |`);
  }
  return out;
}

function renderReddit(d: any): string[] {
  const out = [`- Mentions (unique posts): ${d.mentions?.total ?? 0}`, '', 'Mentions by keyword:', ''];
  for (const row of d.byKeyword ?? []) {
    out.push(`- ${row.keyword}: ${row.mentions}`);
  }
  out.push('', 'Posts (rollup + link only):', '');
  for (const p of d.posts ?? []) {
    out.push(`- [${p.title}](${p.url}) — r/${p.subreddit} (score ${p.score})`);
  }
  return out;
}

function renderRichpanel(d: any): string[] {
  const out = [`- Ticket volume: ${d.ticketVolume}`, '', 'Top themes:', ''];
  for (const row of d.topThemes ?? []) {
    out.push(`- ${row.theme}: ${row.count}`);
  }
  out.push('', 'Top tags:', '');
  for (const row of d.topTags ?? []) {
    out.push(`- ${row.tag}: ${row.count}`);
  }
  return out;
}

function renderAircall(d: any): string[] {
  const out = [
    `- Call count: ${d.callCount}`,
    `- Total duration: ${d.totalDurationSeconds}s (avg ${d.avgDurationSeconds}s)`,
    '',
    'Dispositions:',
    '',
  ];
  for (const row of d.dispositions ?? []) {
    out.push(`- ${row.disposition}: ${row.count}`);
  }
  return out;
}
